apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.amazonEC2MetadataMock.label }}
spec:
  selector:
    app: {{ .Values.amazonEC2MetadataMock.label }}
  ports:
  - port: {{ .Values.settings.port }}
    protocol: TCP
