#! /usr/bin/env bash

set -euo pipefail

SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
EXIT_CODE_TO_RETURN=0

function get_status() {
  pod=$1
  status=$(kubectl describe pod $pod | grep "Status:")
  status=${status//"Status:"/}
  status=$(echo $status | xargs)
  echo $status
}

function assert_value() {
  # assert actual == expected
  if [[ $1 == "$2" ]]; then
    echo "✅ Verified $3"
  else
    echo "❌ Failed $3 verification. Actual: $1 Expected: $2"
    EXIT_CODE_TO_RETURN=1
  fi
}

function clean_up() {
  kubectl delete pods/test-pod pods/test-pod-404
}

function test() {
  num_nodes=$1
  expected_test_pod_status=$2
  expected_test_pod_404_status=$3
  echo "executing term-nodes test with terminationNodes=$num_nodes"

  helm upgrade --install "$CLUSTER_NAME-aemm" \
    $AEMM_HELM_REPO \
    --wait \
    --namespace default \
    --values $AEMM_HELM_REPO/ci/local-image-values.yaml \
    --set aemm.spot.time="1994-05-15T00:00:00Z" \
    --set aemm.terminationNodes=$num_nodes

    # Deploy pods
    kubectl apply -f "$SCRIPTPATH/test-pod.yaml"
    sleep 1
    kubectl apply -f "$SCRIPTPATH/test-pod-404.yaml"

    # Proceed with copying only after pod is Running
    test_pod_404_status=$(get_status test-pod-404)
    while [ "$test_pod_404_status" != "Running" ]; do
      echo "test_pod_404_status: $test_pod_404_status"
      sleep 1
      test_pod_404_status=$(get_status test-pod-404)
    done

    echo "test_pod_404_status: $test_pod_404_status"
    echo "copying to 404-pod..."
    kubectl cp "$SCRIPTPATH/../../e2e/golden/404_response.golden" test-pod-404:/tmp/404_response.golden

    test_pod_status=$(get_status test-pod)
    test_pod_404_status=$(get_status test-pod-404)

    # Keep querying status until tests succeed or fail
    while [ "$test_pod_status" == "Running" ] || [ "$test_pod_404_status" == "Running" ]; do
      test_pod_status=$(get_status test-pod)
      test_pod_404_status=$(get_status test-pod-404)
    done

    assert_value "$test_pod_status" "$expected_test_pod_status" "test-pod $expected_test_pod_status w/terminationNodes=$num_nodes"
    assert_value "$test_pod_404_status" "$expected_test_pod_404_status" "test-pod-404 $expected_test_pod_404_status w/terminationNodes=$num_nodes"

    clean_up
}

echo "======================================================================================================"
echo "🥑 Starting AEMM terimation-nodes test"
echo "======================================================================================================"

test 1 "Succeeded" "Succeeded" # 404 returned after ONE pod Spot request
test 2 "Succeeded" "Failed" # 404 returned after TWO pod Spot requests

exit $EXIT_CODE_TO_RETURN