#!/bin/bash

# Script to generate the helm chart archives for charts in REPO/helm

set -euo pipefail

REPO_ROOT_PATH="$( cd "$(dirname "$0")"; cd ../ ; pwd -P )"
MAKEFILE_PATH=$REPO_ROOT_PATH/Makefile
VERSION=$(make -s -f $MAKEFILE_PATH version)
HELM_CHART_PATH=$REPO_ROOT_PATH/helm
BUILD_DIR=$REPO_ROOT_PATH/build/k8s-resources/$VERSION
HELM_CHART_ARCHIVES_DIR=$BUILD_DIR/helm-chart-archives
mkdir -p $HELM_CHART_ARCHIVES_DIR

for c in $HELM_CHART_PATH/*; do
    if [ -d $c ]; then
        chart_dir=$(echo $c | tr '/' '\n' | tail -1)
        echo "Generating Helm archive for $chart_dir"
        chart_version=`sed -n 's/version: //p' $c/Chart.yaml`

        archive_name="$chart_dir-$chart_version.tgz"
        cd $HELM_CHART_ARCHIVES_DIR
        tar -C $HELM_CHART_PATH -zcf $archive_name $chart_dir
    fi
done

echo -e "\nGenerated Helm chart archives in $HELM_CHART_ARCHIVES_DIR:"
for archive in $HELM_CHART_ARCHIVES_DIR/*; do
    echo "    - $(echo $archive | tr '/' '\n' | tail -1)"
done
