#!/bin/bash

# Script to verify that AEMM version is updated to reflect the latest release in:
## - helm charts' Chart.yaml
## - helm charts' values.yaml
## - README.md

set -uo pipefail

REPOPATH="$( cd "$(dirname "$0")"; cd ../../; pwd -P )"
MAKEFILEPATH=$REPOPATH/Makefile
LATEST_VERSION=$(make -s -f $MAKEFILEPATH latest-tag)
SECOND_LATEST_VERSION=$(make -s -f $MAKEFILEPATH second-latest-tag)

print_note() {
    if [ $? != '0' ]; then
        echo "NOTE: Use \`make update-versions-for-release\` to update AEMM and Helm chart versions in preparation of a release."
        exit 1
    else
        echo "✅ AEMM version ($LATEST_VERSION) was successfully verified in Helm chart and README ✅"
        exit 0
    fi
}

trap 'print_note' EXIT

# Verify version in README
README_HAS_INCORRECT_TAG=$(cat $REPOPATH/README.md | grep $SECOND_LATEST_VERSION)
if [[ ! -z  $README_HAS_INCORRECT_TAG ]]; then
    echo "❌ Please update the AEMM version in README.md. Expected version $LATEST_VERSION, but got $SECOND_LATEST_VERSION ❌"
fi

# Verify version in Helm charts 
HELM_CHART_PATH=$REPOPATH/helm
for c in $HELM_CHART_PATH/*; do
    chart_name=$(echo $c | tr '/' '\n' | tail -1)
    if [ -d $c ]; then

        # verify AEMM version in Chart/yaml
        # note: appVersion in Chart.yaml is informational only
        app_version=$(sed -n 's/appVersion: //p' $c/Chart.yaml)
        if [[ $app_version != $LATEST_VERSION ]]; then
            echo "❌ Please update the appVersion in $chart_name helm chart's Chart.yaml and increment the chart version, if not already done. Expected version $LATEST_VERSION, but got $app_version ❌"
        fi

        # verify AEMM version in values.yaml in order to test the latest release
        values_image_tag=$(sed -n 's/[^\s]tag: //p' $c/values.yaml | tr -d '""' | tr -d ' ')
        if [[ $values_image_tag != $LATEST_VERSION ]]; then
            echo "❌ Please update the release version in $chart_name helm chart's values.yaml, image.tag field and increment the chart version, if not already done. Expected version $LATEST_VERSION, but got $values_image_tag ❌"
            exit 1
        fi
    fi
done